/*
Implement for test.Service
This file is generated by github.com/Hexilee/impler at 2018-10-13 14:53:48.824061 +0800 CST m=+0.140311809
DON'T EDIT IT!
*/

package test

import (
	"net/http"
	"time"
)

func NewService() Service {
	return &serviceImpl{}
}

type serviceImpl struct {
	baseUrl string
	header  http.Header
	cookies []*http.Cookie
}

func (service serviceImpl) UpdateItem(id int, cookie string, data *time.Time) (*UploadResult, int, err) {
	return
}
func (service serviceImpl) UploadItem(path string, contentType string, cookie string) (*http.Response, err) {
	return
}
func (service serviceImpl) GetItem(token int, page int, limit int) (*http.Response, err) {
	return
}
