/*
Implement of test.Service
This file is generated by github.com/Hexilee/impler at 2018-10-13 16:00:28.420306 +0800 CST m=+0.375578627
DON'T EDIT IT!
*/

package test

import (
	"net/http"
	"time"
)

func NewService() Service {
	service := &serviceImpl{
		baseUrl: "https://box.zjuqsc.com/item",
		cookies: make([]*http.Cookie, 0),
		header:  make(http.Header),
	}
	service.header.Add("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36")
	return service
}

type serviceImpl struct {
	baseUrl string
	header  http.Header
	cookies []*http.Cookie
}

func (service serviceImpl) GetItem(token int, page int, limit int) (result *http.Response, err error) {
	return
}
func (service serviceImpl) UpdateItem(id int, cookie string, data *time.Time) (result *UploadResult, statusCode int, err error) {
	return
}
func (service serviceImpl) UploadItem(path string, contentType string, cookie string) (result *http.Response, err error) {
	return
}
