package impl

import (
	"fmt"
	"github.com/dave/jennifer/jen"
	"time"
)

func Impl(service *Service, pkg string) string {
	file := jen.NewFilePath(pkg)
	file.HeaderComment(fmt.Sprintf(`Implement for %s.%s
This file is generated by github.com/Hexilee/impler at %s
DON'T EDIT IT!
`, pkg, service.name, time.Now()))



	return fmt.Sprintf("%#v", file)
}
